resources:
- repo: self
  clean: true
queue:
  name: Hosted Linux Preview
steps:
- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: AzureContainerRegistry
    dockerFile: 'app/api/Dockerfile'
    imageName: '$(Build.Repository.Name)/api:$(Build.SourceVersion)'

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: AzureContainerRegistry
    dockerFile: 'app/web/Dockerfile'
    imageName: '$(Build.Repository.Name)/web:$(Build.SourceVersion)'

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: AzureContainerRegistry
    action: 'Push an image'
    imageName: '$(Build.Repository.Name)/api:$(Build.SourceVersion)'

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: AzureContainerRegistry
    action: 'Push an image'
    imageName: '$(Build.Repository.Name)/web:$(Build.SourceVersion)'

